name: Ruby

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version
        bundler-cache: true
    - uses: Borales/actions-yarn@v4
      with:
        cmd: install

    - name: Run Brakeman
      run: gem install brakeman && brakeman

    - name: Run Tests
      run: bundle exec rake